### ISSUE TITLE
Sonar-exporter is not working !!!

### ISSUE THREAD

**Issue by dungnt081191** [akawork/Sonar-Exporter#3]
Hi everyone , 
Currently Sonar-exporter is not working

Here are detail step and exception log : 

step1 : build image as instruction 
step2 : run image with docker command : 
```
docker run -p 9119:9119 --name sonar-exporter -d -e "SONAR_SERVER=http://sonar-url-here" -e "SONAR_USERNAME=user-here" -e "SONAR_PASSWORD=password-here" dungnt081191/sonar-exporter:1.0
```

Check container logs:
```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    REGISTRY.register(sonar_collector)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "/root/sonar/sonar.py", line 41, in collect
    insecure=True
  File "/root/sonar/sonar.py", line 23, in __init__
    self.projects = Projects(self)
  File "/root/sonar/data/projects.py", line 15, in __init__
    list_status = get_list_projects(sonar)
  File "/root/sonar/data/projects.py", line 73, in get_list_projects
    raw_data = response.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

@namnh68  @hieupmse05244

**Comment by kad-meedel** [comment]
Any answer on this issue yet? I get the same.
I am working within a wsl2 environment on windows

**Comment by eliassal** [comment]
i, how this can be used to create a dasboard in Grafana?
Did you get any response? Is this compatible with version s 9.xx?
